made tasks for 2 & 3 modules
js-tasks-ru/jsbasic-20220418-2_semyon46 pull request #4
Opened 2022-04-23 16:33 UTC by 7on999

2022-04-23 16:34 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-24 11:51 UTC, SinimaWath requested changes

2022-04-24 11:51 UTC, SinimaWath commented on 2-module/1-task/index.js
> +console.log(sumSalary(a))
из задачи стоит убирать код, для тестирования

2022-04-24 11:51 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  }
Лишняя проверка, ее стоит заменить на: `return filterArrValues.reduce((a,b)=>a+b, 0),` - добавил параметр по-умолчанию в reduce

2022-04-24 11:51 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  const res = usersFilteredByAge.map((u,i)=> usersFilteredByAge.length-1===i? u.name+', '+u.balance: u.name+', '+u.balance + '\n')
Давай тут использовать шаблонную строку

2022-04-24 11:51 UTC, SinimaWath commented on 3-module/5-task/index.js
> +console.log(getMinMax(test))
Этот код стоит убрать

2022-04-24 20:15 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-04-24 20:16 UTC, closed without merging

2022-04-24 20:16 UTC, 7on999 commented
Замечания принял